### PR TITLE
release numpy version restriction for python3.10

### PR DESCRIPTION
**Pull request by videodanchik**
Continuing https://github.com/danpovey/lilcom/issues/51 I try to remove `numpy` version restriction for python 3.10.

### CODE REVIEW

**Comment by videodanchik** [comment]
@csukuangfj looks like I didn't break anything, but it will help me with installation through PyPI.

**Comment by csukuangfj** [comment]
@videodanchik 
Thanks! Let us wait for the checks at https://github.com/csukuangfj/lilcom/actions
(It is for building conda packages)

**Comment by csukuangfj** [comment]
Thanks! All tests passed!

**Comment by videodanchik** [comment]
@csukuangfj many thanks, do you think it's possible to make a minor version update and make a release with `lilcom==1.5.1`? If it's not much of an effort, I would really appreciate it.

**Comment by csukuangfj** [comment]
> @csukuangfj many thanks, do you think it's possible to make a minor version update and make a release with `lilcom==1.5.1`? If it's not much of an effort, I would really appreciate it.

sure

**Comment by csukuangfj** [comment]
> @csukuangfj many thanks, do you think it's possible to make a minor version update and make a release with `lilcom==1.5.1`? If it's not much of an effort, I would really appreciate it.

Done.

**Pull request merged**
